### ISSUE TITLE
$ is not a function error

### ISSUE THREAD

**Issue by andrewminton** [Petertron/workspacer#2]
https://github.com/Petertron/workspacer/blob/master/assets/editor.js#L158

This line is causing an error for some reason. making the workspace editorframe unresponsive. MIx of jQuery declarations maybe? JQuery confuses me so wouldn't know where to start.

**Comment by petertron** [comment]
Somehow I've had no such problem, and that is with Firefox and Chrome. I have uploaded a slightly altered version.
