### ISSUE TITLE
Page not found on nginx with 2.6.6

### ISSUE THREAD

**Issue by moretaste** [Petertron/workspacer#4]
All urls from the extension gives a 404 page not found on nginx server

**Comment by petertron** [comment]
I have uploaded version 0.3.1. The "page not found" problem would have happened with other servers, except for Hiawatha, the server I use.

**Comment by moretaste** [comment]
This version fix it, thanks

**Comment by moretaste** [comment]
One files with a .php extension (like data-sources) gives a file not found.

**Comment by petertron** [comment]
It should have occurred to me that this might happen. The problem was the same as before -- the file path contained a double slash. My server tolerates double slashes, which is perhaps a bad thing.

Version 0.3.2 uploaded.

**Comment by moretaste** [comment]
Doesn't fix the issue for me with .php files

**Comment by petertron** [comment]
There is nothing in my code that would obviously cause PHP files to not be found. I used nginx in the past and I never had this problem.

**Comment by moretaste** [comment]
Ok, probably it is a php-fastcgi setting that doesn't allow to view the contents of a php file. If I have time I will try to figure it out
