### ISSUE TITLE
Unable to edit files [ Workspacer 0.4 + Smyphony 2.6.11 ]

### ISSUE THREAD

**Issue by twiro** [Petertron/workspacer#5]
I'm unable to edit files (I've tried XSL, CSS and JS) because whenever I try to type in the editor the following two Javascript-errors are thrown:

    TypeError: $ is not a function
    $(document).ready(function() {

in **.../workspacer/editor_js/** _(Line 104)_

    TypeError: parent.window.displayLineNumbers is not a function
    return parent.window.displayLineNumbers(num_lines);

in **.../workspacer/assets/editorframe.js** _(Line 440)_

I'm using latest Firefox (45) on a Mac.

**Comment by petertron** [comment]
The latest Firefox is 54. Somehow I do not get the errors that you are getting. I have made a small change to `editor.js` which I hope will fix the problem.
