### ISSUE TITLE
Crashes when there are symbolic links in workspace folder

### ISSUE THREAD

**Issue by peterfleck** [Petertron/workspacer#6]
On Bitnami Windows WAMP stack, Symphony lts/2.7.10

![symlink-workspacer](https://user-images.githubusercontent.com/22399752/66899023-2d247980-eff2-11e9-9339-eb3e469a2a64.PNG)

**Comment by petertron** [comment]
A new version has been uploaded.

**Comment by peterfleck** [comment]
thanks. 👍
